<?php
array(	1 => array('name_ru' => 'Австралия', 'name_en' => 'Australia', 'iso2_alpha_code' => '1'),
		2 => array('name_ru' => 'Малайзия', 'name_en' => 'Malaysia', 'iso2_alpha_code' => '2'),
		3 => array('name_ru' => 'Республика Корея', 'name_en' => 'Korea', 'iso2_alpha_code' => '3'),
		4 => array('name_ru' => 'Китай', 'name_en' => 'China', 'iso2_alpha_code' => '4'),
		5 => array('name_ru' => 'Япония', 'name_en' => 'Japan', 'iso2_alpha_code' => '5'),
		6 => array('name_ru' => 'Индия', 'name_en' => 'India', 'iso2_alpha_code' => '6'),
		7 => array('name_ru' => 'Тайвань', 'name_en' => 'Taiwan', 'iso2_alpha_code' => '7'),
		8 => array('name_ru' => 'Гонконг', 'name_en' => 'Hong Kong', 'iso2_alpha_code' => '8'),
		9 => array('name_ru' => 'Таиланд', 'name_en' => 'Thailand', 'iso2_alpha_code' => '9'),
		11 => array('name_ru' => 'Вьетнам', 'name_en' => 'Vietnam', 'iso2_alpha_code' => '11'),
		12 => array('name_ru' => 'Франция', 'name_en' => 'France', 'iso2_alpha_code' => '12'),
		13 => array('name_ru' => 'Италия', 'name_en' => 'Italy', 'iso2_alpha_code' => '13'),
		14 => array('name_ru' => 'Объединенные Арабские Эмираты', 'name_en' => 'United Arab Emirates', 'iso2_alpha_code' => '14'),
		15 => array('name_ru' => 'Швеция', 'name_en' => 'Sweden', 'iso2_alpha_code' => '15'),
		16 => array('name_ru' => 'Казахстан', 'name_en' => 'Kazakhstan', 'iso2_alpha_code' => '16'),
		17 => array('name_ru' => 'Португалия', 'name_en' => 'Portugal', 'iso2_alpha_code' => '17'),
		18 => array('name_ru' => 'Греция', 'name_en' => 'Greece', 'iso2_alpha_code' => '18'),
		19 => array('name_ru' => 'Саудовская Аравия', 'name_en' => 'Saudi Arabia', 'iso2_alpha_code' => '19'),
		20 => array('name_ru' => 'Российская Федерация', 'name_en' => 'Russian Federation', 'iso2_alpha_code' => '20'),
		21 => array('name_ru' => 'Великобритания', 'name_en' => 'United Kingdom', 'iso2_alpha_code' => '21'),
		22 => array('name_ru' => 'Дания', 'name_en' => 'Denmark', 'iso2_alpha_code' => '22'),
		23 => array('name_ru' => 'США', 'name_en' => 'United States', 'iso2_alpha_code' => '23'),
		24 => array('name_ru' => 'Канада', 'name_en' => 'Canada', 'iso2_alpha_code' => '24'),
		25 => array('name_ru' => 'Мексика', 'name_en' => 'Mexico', 'iso2_alpha_code' => '25'),
		26 => array('name_ru' => 'Бермуды', 'name_en' => 'Bermuda', 'iso2_alpha_code' => '26'),
		27 => array('name_ru' => 'Пуэрто Рико', 'name_en' => 'Puerto Rico', 'iso2_alpha_code' => '27'),
		28 => array('name_ru' => 'Виргинские Острова США', 'name_en' => 'Virgin Islands, U.S.', 'iso2_alpha_code' => '28'),
		29 => array('name_ru' => 'Германия', 'name_en' => 'Germany', 'iso2_alpha_code' => '29'),
		30 => array('name_ru' => 'Иран', 'name_en' => 'Iran', 'iso2_alpha_code' => '30'),
		31 => array('name_ru' => 'Боливия', 'name_en' => 'Bolivia', 'iso2_alpha_code' => '31'),
		32 => array('name_ru' => 'Монтсеррат', 'name_en' => 'Montserrat', 'iso2_alpha_code' => '32'),
		33 => array('name_ru' => 'Нидерланды', 'name_en' => 'Netherlands', 'iso2_alpha_code' => '33'),
		34 => array('name_ru' => 'Израиль', 'name_en' => 'Israel', 'iso2_alpha_code' => '34'),
		35 => array('name_ru' => 'Испания', 'name_en' => 'Spain', 'iso2_alpha_code' => '35'),
		36 => array('name_ru' => 'Багамские острова', 'name_en' => 'Bahamas', 'iso2_alpha_code' => '36'),
		37 => array('name_ru' => 'Сент-Винсент и Гренадины', 'name_en' => 'Saint Vincent and the Grenadines', 'iso2_alpha_code' => '37'),
		38 => array('name_ru' => 'Чили', 'name_en' => 'Chile', 'iso2_alpha_code' => '38'),
		39 => array('name_ru' => 'Новая Каледония', 'name_en' => 'New Caledonia', 'iso2_alpha_code' => '39'),
		40 => array('name_ru' => 'Аргентина', 'name_en' => 'Argentina', 'iso2_alpha_code' => '40'),
		41 => array('name_ru' => 'Доминика', 'name_en' => 'Dominica', 'iso2_alpha_code' => '41'),
		42 => array('name_ru' => 'Сингапур', 'name_en' => 'Singapore', 'iso2_alpha_code' => '42'),
		43 => array('name_ru' => 'Непал', 'name_en' => 'Nepal', 'iso2_alpha_code' => '43'),
		44 => array('name_ru' => 'Филиппины', 'name_en' => 'Philippines', 'iso2_alpha_code' => '44'),
		45 => array('name_ru' => 'Индонезия', 'name_en' => 'Indonesia', 'iso2_alpha_code' => '45'),
		46 => array('name_ru' => 'Пакистан', 'name_en' => 'Pakistan', 'iso2_alpha_code' => '46'),
		47 => array('name_ru' => 'Токелау', 'name_en' => 'Tokelau', 'iso2_alpha_code' => '47'),
		48 => array('name_ru' => 'Новая Зеландия', 'name_en' => 'New Zealand', 'iso2_alpha_code' => '48'),
		49 => array('name_ru' => 'Камбоджа', 'name_en' => 'Cambodia', 'iso2_alpha_code' => '49'),
		50 => array('name_ru' => 'Макау', 'name_en' => 'Macau', 'iso2_alpha_code' => '50'),
		51 => array('name_ru' => 'Папуа Новая Гвинея', 'name_en' => 'Papua New Guinea', 'iso2_alpha_code' => '51'),
		52 => array('name_ru' => 'Мальдивские острова', 'name_en' => 'Maldives', 'iso2_alpha_code' => '52'),
		53 => array('name_ru' => 'Афганистан', 'name_en' => 'Afghanistan', 'iso2_alpha_code' => '53'),
		54 => array('name_ru' => 'Бангладеш', 'name_en' => 'Bangladesh', 'iso2_alpha_code' => '54'),
		55 => array('name_ru' => 'Ирландия', 'name_en' => 'Ireland', 'iso2_alpha_code' => '55'),
		56 => array('name_ru' => 'Бельгия', 'name_en' => 'Belgium', 'iso2_alpha_code' => '56'),
		57 => array('name_ru' => 'Белиз', 'name_en' => 'Belize', 'iso2_alpha_code' => '57'),
		58 => array('name_ru' => 'Бразилия', 'name_en' => 'Brazil', 'iso2_alpha_code' => '58'),
		59 => array('name_ru' => 'Швейцария', 'name_en' => 'Switzerland', 'iso2_alpha_code' => '59'),
		60 => array('name_ru' => 'Южно-Африканская Республика', 'name_en' => 'South Africa', 'iso2_alpha_code' => '60'),
		61 => array('name_ru' => 'Египет', 'name_en' => 'Egypt', 'iso2_alpha_code' => '61'),
		62 => array('name_ru' => 'Нигерия', 'name_en' => 'Nigeria', 'iso2_alpha_code' => '62'),
		63 => array('name_ru' => 'Танзания', 'name_en' => 'Tanzania', 'iso2_alpha_code' => '63'),
		64 => array('name_ru' => 'Замбия', 'name_en' => 'Zambia', 'iso2_alpha_code' => '64'),
		65 => array('name_ru' => 'Сенегал', 'name_en' => 'Senegal', 'iso2_alpha_code' => '65'),
		66 => array('name_ru' => 'Гана', 'name_en' => 'Ghana', 'iso2_alpha_code' => '66'),
		67 => array('name_ru' => 'Судан', 'name_en' => 'Sudan', 'iso2_alpha_code' => '67'),
		68 => array('name_ru' => 'Камерун', 'name_en' => 'Cameroon', 'iso2_alpha_code' => '68'),
		69 => array('name_ru' => 'Малави', 'name_en' => 'Malawi', 'iso2_alpha_code' => '69'),
		70 => array('name_ru' => 'Ангола', 'name_en' => 'Angola', 'iso2_alpha_code' => '70'),
		71 => array('name_ru' => 'Кения', 'name_en' => 'Kenya', 'iso2_alpha_code' => '71'),
		72 => array('name_ru' => 'Габон', 'name_en' => 'Gabon', 'iso2_alpha_code' => '72'),
		73 => array('name_ru' => 'Мали', 'name_en' => 'Mali', 'iso2_alpha_code' => '73'),
		74 => array('name_ru' => 'Бенин', 'name_en' => 'Benin', 'iso2_alpha_code' => '74'),
		75 => array('name_ru' => 'Мадагаскар', 'name_en' => 'Madagascar', 'iso2_alpha_code' => '75'),
		76 => array('name_ru' => 'Чад', 'name_en' => 'Chad', 'iso2_alpha_code' => '76'),
		77 => array('name_ru' => 'Ботсвана', 'name_en' => 'Botswana', 'iso2_alpha_code' => '77'),
		78 => array('name_ru' => 'Ливия', 'name_en' => 'Libya', 'iso2_alpha_code' => '78'),
		79 => array('name_ru' => 'Кабо-Верде', 'name_en' => 'Cape Verde', 'iso2_alpha_code' => '79'),
		80 => array('name_ru' => 'Руанда', 'name_en' => 'Rwanda', 'iso2_alpha_code' => '80'),
		81 => array('name_ru' => 'Мозамбик', 'name_en' => 'Mozambique', 'iso2_alpha_code' => '81'),
		82 => array('name_ru' => 'Гамбия', 'name_en' => 'Gambia', 'iso2_alpha_code' => '82'),
		83 => array('name_ru' => 'Лесото', 'name_en' => 'Lesotho', 'iso2_alpha_code' => '83'),
		84 => array('name_ru' => 'Маврикий', 'name_en' => 'Mauritius', 'iso2_alpha_code' => '84'),
		85 => array('name_ru' => 'Конго', 'name_en' => 'Congo', 'iso2_alpha_code' => '85'),
		86 => array('name_ru' => 'Уганда', 'name_en' => 'Uganda', 'iso2_alpha_code' => '86'),
		87 => array('name_ru' => 'Буркина Фасо', 'name_en' => 'Burkina Faso', 'iso2_alpha_code' => '87'),
		88 => array('name_ru' => 'Сьерра-Леоне', 'name_en' => 'Sierra Leone', 'iso2_alpha_code' => '88'),
		89 => array('name_ru' => 'Сомали', 'name_en' => 'Somalia', 'iso2_alpha_code' => '89'),
		90 => array('name_ru' => 'Зимбабве', 'name_en' => 'Zimbabwe', 'iso2_alpha_code' => '90'),
		91 => array('name_ru' => 'Демократическая Республика Конго', 'name_en' => 'Democratic Republic Of The Congo', 'iso2_alpha_code' => '91'),
		92 => array('name_ru' => 'Нигер', 'name_en' => 'Niger', 'iso2_alpha_code' => '92'),
		93 => array('name_ru' => 'Центрально-Африканская Республика', 'name_en' => 'Central African Republic', 'iso2_alpha_code' => '93'),
		94 => array('name_ru' => 'Свазиленд', 'name_en' => 'Swaziland', 'iso2_alpha_code' => '94'),
		95 => array('name_ru' => 'Того', 'name_en' => 'Togo', 'iso2_alpha_code' => '95'),
		96 => array('name_ru' => 'Гвинея', 'name_en' => 'Guinea', 'iso2_alpha_code' => '96'),
		97 => array('name_ru' => 'Либерия', 'name_en' => 'Liberia', 'iso2_alpha_code' => '97'),
		98 => array('name_ru' => 'Сейшеллы', 'name_en' => 'Seychelles', 'iso2_alpha_code' => '98'),
		99 => array('name_ru' => 'Марокко', 'name_en' => 'Morocco', 'iso2_alpha_code' => '99'),
		100 => array('name_ru' => 'Алжир', 'name_en' => 'Algeria', 'iso2_alpha_code' => '100'),
		101 => array('name_ru' => 'Мавритания', 'name_en' => 'Mauritania', 'iso2_alpha_code' => '101'),
		102 => array('name_ru' => 'Намибия', 'name_en' => 'Namibia', 'iso2_alpha_code' => '102'),
		103 => array('name_ru' => 'Джибути', 'name_en' => 'Djibouti', 'iso2_alpha_code' => '103'),
		105 => array('name_ru' => 'Коморские острова', 'name_en' => 'Comoros', 'iso2_alpha_code' => '105'),
		106 => array('name_ru' => 'Реюньон', 'name_en' => 'Reunion', 'iso2_alpha_code' => '106'),
		107 => array('name_ru' => 'Экваториальная Гвинея', 'name_en' => 'Equatorial Guinea', 'iso2_alpha_code' => '107'),
		108 => array('name_ru' => 'Тунис', 'name_en' => 'Tunisia', 'iso2_alpha_code' => '108'),
		109 => array('name_ru' => 'Турция', 'name_en' => 'Turkey', 'iso2_alpha_code' => '109'),
		110 => array('name_ru' => 'Польша', 'name_en' => 'Poland', 'iso2_alpha_code' => '110'),
		111 => array('name_ru' => 'Латвия', 'name_en' => 'Latvia', 'iso2_alpha_code' => '111'),
		112 => array('name_ru' => 'Украина', 'name_en' => 'Ukraine', 'iso2_alpha_code' => '112'),
		113 => array('name_ru' => 'Беларусь', 'name_en' => 'Belarus', 'iso2_alpha_code' => '113'),
		114 => array('name_ru' => 'Чехия', 'name_en' => 'Czech Republic', 'iso2_alpha_code' => '114'),
		115 => array('name_ru' => 'Палестина', 'name_en' => 'Palestinian Territory', 'iso2_alpha_code' => '115'),
		116 => array('name_ru' => 'Исландия', 'name_en' => 'Iceland', 'iso2_alpha_code' => '116'),
		117 => array('name_ru' => 'Кипр', 'name_en' => 'Cyprus', 'iso2_alpha_code' => '117'),
		118 => array('name_ru' => 'Венгрия', 'name_en' => 'Hungary', 'iso2_alpha_code' => '118'),
		119 => array('name_ru' => 'Словакия', 'name_en' => 'Slovakia', 'iso2_alpha_code' => '119'),
		120 => array('name_ru' => 'Сербия', 'name_en' => 'Serbia', 'iso2_alpha_code' => '120'),
		121 => array('name_ru' => 'Болгария', 'name_en' => 'Bulgaria', 'iso2_alpha_code' => '121'),
		122 => array('name_ru' => 'Оман', 'name_en' => 'Oman', 'iso2_alpha_code' => '122'),
		123 => array('name_ru' => 'Румыния', 'name_en' => 'Romania', 'iso2_alpha_code' => '123'),
		124 => array('name_ru' => 'Грузия', 'name_en' => 'Georgia', 'iso2_alpha_code' => '124'),
		125 => array('name_ru' => 'Норвегия', 'name_en' => 'Norway', 'iso2_alpha_code' => '125'),
		126 => array('name_ru' => 'Армения', 'name_en' => 'Armenia', 'iso2_alpha_code' => '126'),
		127 => array('name_ru' => 'Австрия', 'name_en' => 'Austria', 'iso2_alpha_code' => '127'),
		128 => array('name_ru' => 'Албания', 'name_en' => 'Albania', 'iso2_alpha_code' => '128'),
		129 => array('name_ru' => 'Словения', 'name_en' => 'Slovenia', 'iso2_alpha_code' => '129'),
		130 => array('name_ru' => 'Панама', 'name_en' => 'Panama', 'iso2_alpha_code' => '130'),
		131 => array('name_ru' => 'Бруней', 'name_en' => 'Brunei Darussalam', 'iso2_alpha_code' => '131'),
		132 => array('name_ru' => 'Шри-Ланка', 'name_en' => 'Sri Lanka', 'iso2_alpha_code' => '132'),
		133 => array('name_ru' => 'Черногория', 'name_en' => 'Montenegro', 'iso2_alpha_code' => '133'),
		134 => array('name_ru' => 'Европейский Союз', 'name_en' => 'Europe', 'iso2_alpha_code' => '134'),
		135 => array('name_ru' => 'Таджикистан', 'name_en' => 'Tajikistan', 'iso2_alpha_code' => '135'),
		136 => array('name_ru' => 'Ирак', 'name_en' => 'Iraq', 'iso2_alpha_code' => '136'),
		137 => array('name_ru' => 'Ливан', 'name_en' => 'Lebanon', 'iso2_alpha_code' => '137'),
		138 => array('name_ru' => 'Молдова', 'name_en' => 'Moldova', 'iso2_alpha_code' => '138'),
		139 => array('name_ru' => 'Финляндия', 'name_en' => 'Finland', 'iso2_alpha_code' => '139'),
		140 => array('name_ru' => 'Эстония', 'name_en' => 'Estonia', 'iso2_alpha_code' => '140'),
		141 => array('name_ru' => 'Босния и Герцеговина', 'name_en' => 'Bosnia and Herzegovina', 'iso2_alpha_code' => '141'),
		142 => array('name_ru' => 'Кувейт', 'name_en' => 'Kuwait', 'iso2_alpha_code' => '142'),
		143 => array('name_ru' => 'Аландские острова', 'name_en' => 'Aland Islands', 'iso2_alpha_code' => '143'),
		144 => array('name_ru' => 'Литва', 'name_en' => 'Lithuania', 'iso2_alpha_code' => '144'),
		145 => array('name_ru' => 'Люксембург', 'name_en' => 'Luxembourg', 'iso2_alpha_code' => '145'),
		146 => array('name_ru' => 'Антигуа и Барбуда', 'name_en' => 'Antigua and Barbuda', 'iso2_alpha_code' => '146'),
		147 => array('name_ru' => 'Македония', 'name_en' => 'Macedonia', 'iso2_alpha_code' => '147'),
		148 => array('name_ru' => 'Сан-Марино', 'name_en' => 'San Marino', 'iso2_alpha_code' => '148'),
		149 => array('name_ru' => 'Мальта', 'name_en' => 'Malta', 'iso2_alpha_code' => '149'),
		150 => array('name_ru' => 'Фолклендские острова', 'name_en' => 'Falkland Islands', 'iso2_alpha_code' => '150'),
		151 => array('name_ru' => 'Бахрейн', 'name_en' => 'Bahrain', 'iso2_alpha_code' => '151'),
		152 => array('name_ru' => 'Узбекистан', 'name_en' => 'Uzbekistan', 'iso2_alpha_code' => '152'),
		153 => array('name_ru' => 'Азербайджан', 'name_en' => 'Azerbaijan', 'iso2_alpha_code' => '153'),
		154 => array('name_ru' => 'Монако', 'name_en' => 'Monaco', 'iso2_alpha_code' => '154'),
		155 => array('name_ru' => 'Гаити', 'name_en' => 'Haiti', 'iso2_alpha_code' => '155'),
		156 => array('name_ru' => 'Гуам', 'name_en' => 'Guam', 'iso2_alpha_code' => '156'),
		157 => array('name_ru' => 'Ямайка', 'name_en' => 'Jamaica', 'iso2_alpha_code' => '157'),
		158 => array('name_ru' => 'Внешние малые острова США', 'name_en' => 'United States Minor Outlying Islands', 'iso2_alpha_code' => '158'),
		159 => array('name_ru' => 'Микронезия', 'name_en' => 'Micronesia', 'iso2_alpha_code' => '159'),
		160 => array('name_ru' => 'Эквадор', 'name_en' => 'Ecuador', 'iso2_alpha_code' => '160'),
		161 => array('name_ru' => 'Перу', 'name_en' => 'Peru', 'iso2_alpha_code' => '161'),
		162 => array('name_ru' => 'Каймановы острова', 'name_en' => 'Cayman Islands', 'iso2_alpha_code' => '162'),
		163 => array('name_ru' => 'Колумбия', 'name_en' => 'Colombia', 'iso2_alpha_code' => '163'),
		164 => array('name_ru' => 'Гондурас', 'name_en' => 'Honduras', 'iso2_alpha_code' => '164'),
		165 => array('name_ru' => 'Антильские острова', 'name_en' => 'Netherlands Antilles', 'iso2_alpha_code' => '165'),
		166 => array('name_ru' => 'Йемен', 'name_en' => 'Yemen', 'iso2_alpha_code' => '166'),
		167 => array('name_ru' => 'Британские Виргинские острова', 'name_en' => 'Virgin Islands, British', 'iso2_alpha_code' => '167'),
		168 => array('name_ru' => 'Сирия', 'name_en' => 'Syria', 'iso2_alpha_code' => '168'),
		169 => array('name_ru' => 'Никарагуа', 'name_en' => 'Nicaragua', 'iso2_alpha_code' => '169'),
		170 => array('name_ru' => 'Доминиканская республика', 'name_en' => 'Dominican Republic', 'iso2_alpha_code' => '170'),
		171 => array('name_ru' => 'Гренада', 'name_en' => 'Grenada', 'iso2_alpha_code' => '171'),
		172 => array('name_ru' => 'Гватемала', 'name_en' => 'Guatemala', 'iso2_alpha_code' => '172'),
		173 => array('name_ru' => 'Коста-Рика', 'name_en' => 'Costa Rica', 'iso2_alpha_code' => '173'),
		174 => array('name_ru' => 'Сальвадор', 'name_en' => 'El Salvador', 'iso2_alpha_code' => '174'),
		175 => array('name_ru' => 'Венесуэла', 'name_en' => 'Venezuela', 'iso2_alpha_code' => '175'),
		176 => array('name_ru' => 'Барбадос', 'name_en' => 'Barbados', 'iso2_alpha_code' => '176'),
		177 => array('name_ru' => 'Тринидад и Тобаго', 'name_en' => 'Trinidad and Tobago', 'iso2_alpha_code' => '177'),
		178 => array('name_ru' => 'Буве', 'name_en' => 'Bouvet Island', 'iso2_alpha_code' => '178'),
		179 => array('name_ru' => 'Маршалловы острова', 'name_en' => 'Marshall Islands', 'iso2_alpha_code' => '179'),
		180 => array('name_ru' => 'Острова Кука', 'name_en' => 'Cook Islands', 'iso2_alpha_code' => '180'),
		181 => array('name_ru' => 'Гибралтар', 'name_en' => 'Gibraltar', 'iso2_alpha_code' => '181'),
		182 => array('name_ru' => 'Парагвай', 'name_en' => 'Paraguay', 'iso2_alpha_code' => '182'),
		184 => array('name_ru' => 'Самоа', 'name_en' => 'Samoa', 'iso2_alpha_code' => '184'),
		185 => array('name_ru' => 'Сент Китс и Невис', 'name_en' => 'Saint Kitts and Nevis', 'iso2_alpha_code' => '185'),
		186 => array('name_ru' => 'Фиджи', 'name_en' => 'Fiji', 'iso2_alpha_code' => '186'),
		187 => array('name_ru' => 'Уругвай', 'name_en' => 'Uruguay', 'iso2_alpha_code' => '187'),
		188 => array('name_ru' => 'Северные Марианские острова', 'name_en' => 'Northern Mariana Islands', 'iso2_alpha_code' => '188'),
		189 => array('name_ru' => 'Палау', 'name_en' => 'Palau', 'iso2_alpha_code' => '189'),
		190 => array('name_ru' => 'Катар', 'name_en' => 'Qatar', 'iso2_alpha_code' => '190'),
		191 => array('name_ru' => 'Иордания', 'name_en' => 'Jordan', 'iso2_alpha_code' => '191'),
		192 => array('name_ru' => 'Американское Самоа', 'name_en' => 'American Samoa', 'iso2_alpha_code' => '192'),
		193 => array('name_ru' => 'Туркс и Кейкос', 'name_en' => 'Turks and Caicos Islands', 'iso2_alpha_code' => '193'),
		194 => array('name_ru' => 'Святая Люсия', 'name_en' => 'Saint Lucia', 'iso2_alpha_code' => '194'),
		195 => array('name_ru' => 'Монголия', 'name_en' => 'Mongolia', 'iso2_alpha_code' => '195'),
		196 => array('name_ru' => 'Ватикан', 'name_en' => 'Holy See', 'iso2_alpha_code' => '196'),
		197 => array('name_ru' => 'Арулько', 'name_en' => 'Aruba', 'iso2_alpha_code' => '197'),
		198 => array('name_ru' => 'Гайана', 'name_en' => 'Guyana', 'iso2_alpha_code' => '198'),
		199 => array('name_ru' => 'Суринам', 'name_en' => 'Suriname', 'iso2_alpha_code' => '199'),
		200 => array('name_ru' => 'Остров Мэн', 'name_en' => 'Isle of Man', 'iso2_alpha_code' => '200'),
		201 => array('name_ru' => 'Вануату', 'name_en' => 'Vanuatu', 'iso2_alpha_code' => '201'),
		202 => array('name_ru' => 'Хорватия', 'name_en' => 'Croatia', 'iso2_alpha_code' => '202'),
		203 => array('name_ru' => 'Ангуилья', 'name_en' => 'Anguilla', 'iso2_alpha_code' => '203'),
		204 => array('name_ru' => 'Сен-Пьер и Микелон', 'name_en' => 'Saint Pierre and Miquelon', 'iso2_alpha_code' => '204'),
		205 => array('name_ru' => 'Гваделупа', 'name_en' => 'Guadeloupe', 'iso2_alpha_code' => '205'),
		206 => array('name_ru' => 'Сен-Мартен', 'name_en' => 'Saint Martin', 'iso2_alpha_code' => '206'),
		207 => array('name_ru' => 'Гернси', 'name_en' => 'Guernsey', 'iso2_alpha_code' => '207'),
		208 => array('name_ru' => 'Бурунди', 'name_en' => 'Burundi', 'iso2_alpha_code' => '208'),
		209 => array('name_ru' => 'Туркменистан', 'name_en' => 'Turkmenistan', 'iso2_alpha_code' => '209'),
		210 => array('name_ru' => 'Кыргызстан', 'name_en' => 'Kyrgyzstan', 'iso2_alpha_code' => '210'),
		211 => array('name_ru' => 'Мьянма', 'name_en' => 'Myanmar', 'iso2_alpha_code' => '211'),
		212 => array('name_ru' => 'Бутан', 'name_en' => 'Bhutan', 'iso2_alpha_code' => '212'),
		213 => array('name_ru' => 'Лихтенштейн', 'name_en' => 'Liechtenstein', 'iso2_alpha_code' => '213'),
		214 => array('name_ru' => 'Фарерские острова', 'name_en' => 'Faroe Islands', 'iso2_alpha_code' => '214'),
		215 => array('name_ru' => 'Эфиопия', 'name_en' => 'Ethiopia', 'iso2_alpha_code' => '215'),
		216 => array('name_ru' => 'Мартиника', 'name_en' => 'Martinique', 'iso2_alpha_code' => '216'),
		217 => array('name_ru' => 'Джерси', 'name_en' => 'Jersey', 'iso2_alpha_code' => '217'),
		218 => array('name_ru' => 'Андорра', 'name_en' => 'Andorra', 'iso2_alpha_code' => '218'),
		219 => array('name_ru' => 'Антарктида', 'name_en' => 'Antarctica', 'iso2_alpha_code' => '219'),
		220 => array('name_ru' => 'Британская территория в Индийском океане', 'name_en' => 'British Indian Ocean Territory', 'iso2_alpha_code' => '220'),
		221 => array('name_ru' => 'Гренландия', 'name_en' => 'Greenland', 'iso2_alpha_code' => '221'),
		222 => array('name_ru' => 'Гвинея-Бисау', 'name_en' => 'Guinea-Bissau', 'iso2_alpha_code' => '222'),
		223 => array('name_ru' => 'Эритрея', 'name_en' => 'Eritrea', 'iso2_alpha_code' => '223'),
		224 => array('name_ru' => 'Уоллис и Футуна', 'name_en' => 'Wallis and Futuna', 'iso2_alpha_code' => '224'),
		225 => array('name_ru' => 'Французская Полинезия', 'name_en' => 'French Polynesia', 'iso2_alpha_code' => '225'),
		226 => array('name_ru' => 'Куба', 'name_en' => 'Cuba', 'iso2_alpha_code' => '226'),
		227 => array('name_ru' => 'Тонга', 'name_en' => 'Tonga', 'iso2_alpha_code' => '227'),
		228 => array('name_ru' => 'Восточный Тимор', 'name_en' => 'Timor-Leste', 'iso2_alpha_code' => '228'),
		229 => array('name_ru' => 'Сан-Томе и Принсипи', 'name_en' => 'Sao Tome and Principe', 'iso2_alpha_code' => '229'),
		230 => array('name_ru' => 'Французская Гвинея', 'name_en' => 'French Guiana', 'iso2_alpha_code' => '230'),
		231 => array('name_ru' => 'Соломоновы острова', 'name_en' => 'Solomon Islands', 'iso2_alpha_code' => '231'),
		232 => array('name_ru' => 'Тувалу', 'name_en' => 'Tuvalu', 'iso2_alpha_code' => '232'),
		233 => array('name_ru' => 'Кирибати', 'name_en' => 'Kiribati', 'iso2_alpha_code' => '233'),
		234 => array('name_ru' => 'Ниуэ', 'name_en' => 'Niue', 'iso2_alpha_code' => '234'),
		235 => array('name_ru' => 'Норфолк', 'name_en' => 'Norfolk Island', 'iso2_alpha_code' => '235'),
		236 => array('name_ru' => 'Науру', 'name_en' => 'Nauru', 'iso2_alpha_code' => '236'),
		237 => array('name_ru' => 'Майотта', 'name_en' => 'Mayotte', 'iso2_alpha_code' => '237'),
		238 => array('name_ru' => 'Питкэрн', 'name_en' => 'Pitcairn Islands', 'iso2_alpha_code' => '238'),
		239 => array('name_ru' => 'Кот-дИвуар', 'name_en' => 'Cote DIvoire', 'iso2_alpha_code' => '239'),
		240 => array('name_ru' => 'Лаос', 'name_en' => 'Lao', 'iso2_alpha_code' => '240'),
		241 => array('name_ru' => 'Корейская Народно-Демократическая Республика', 'name_en' => 'Democratic Peoples Republic of Korea', 'iso2_alpha_code' => '241'),
		242 => array('name_ru' => 'Свальбард и Ян-Майен', 'name_en' => 'Svalbard and Jan Mayen', 'iso2_alpha_code' => '242'),
		243 => array('name_ru' => 'Остров Святой Елены', 'name_en' => 'Saint Helena', 'iso2_alpha_code' => '243'),
		244 => array('name_ru' => 'Кокосовые острова', 'name_en' => 'Cocos (Keeling) Islands', 'iso2_alpha_code' => '244'),
		245 => array('name_ru' => 'Западная Сахара', 'name_en' => 'Western Sahara', 'iso2_alpha_code' => '245'),
		247 => array('name_ru' => 'Южный Судан', 'name_en' => 'South Sudan', 'iso2_alpha_code' => '247')
);
