<?php

array(	1 => array('name_en' => 'Australia', 'name_ru' => 'Австралия', 'iso2_alpha_code' => 'au'),
		2 => array('name_en' => 'Malaysia', 'name_ru' => 'Малайзия', 'iso2_alpha_code' => 'my'),
		3 => array('name_en' => 'Korea', 'name_ru' => 'Республика Корея', 'iso2_alpha_code' => 'kr'),
		4 => array('name_en' => 'China', 'name_ru' => 'Китай', 'iso2_alpha_code' => 'cn'),
		5 => array('name_en' => 'Japan', 'name_ru' => 'Япония', 'iso2_alpha_code' => 'jp'),
		6 => array('name_en' => 'India', 'name_ru' => 'Индия', 'iso2_alpha_code' => 'in'),
		7 => array('name_en' => 'Taiwan', 'name_ru' => 'Тайвань', 'iso2_alpha_code' => 'tw'),
		8 => array('name_en' => 'Hong Kong', 'name_ru' => 'Гонконг', 'iso2_alpha_code' => 'hk'),
		9 => array('name_en' => 'Thailand', 'name_ru' => 'Таиланд', 'iso2_alpha_code' => 'th'),
		11 => array('name_en' => 'Vietnam', 'name_ru' => 'Вьетнам', 'iso2_alpha_code' => 'vn'),
		12 => array('name_en' => 'France', 'name_ru' => 'Франция', 'iso2_alpha_code' => 'fr'),
		13 => array('name_en' => 'Italy', 'name_ru' => 'Италия', 'iso2_alpha_code' => 'it'),
		14 => array('name_en' => 'United Arab Emirates', 'name_ru' => 'Объединенные Арабские Эмираты', 'iso2_alpha_code' => 'ae'),
		15 => array('name_en' => 'Sweden', 'name_ru' => 'Швеция', 'iso2_alpha_code' => 'se'),
		16 => array('name_en' => 'Kazakhstan', 'name_ru' => 'Казахстан', 'iso2_alpha_code' => 'kz'),
		17 => array('name_en' => 'Portugal', 'name_ru' => 'Португалия', 'iso2_alpha_code' => 'pt'),
		18 => array('name_en' => 'Greece', 'name_ru' => 'Греция', 'iso2_alpha_code' => 'gr'),
		19 => array('name_en' => 'Saudi Arabia', 'name_ru' => 'Саудовская Аравия', 'iso2_alpha_code' => 'sa'),
		20 => array('name_en' => 'Russian Federation', 'name_ru' => 'Российская Федерация', 'iso2_alpha_code' => 'ru'),
		21 => array('name_en' => 'United Kingdom', 'name_ru' => 'Великобритания', 'iso2_alpha_code' => 'gb'),
		22 => array('name_en' => 'Denmark', 'name_ru' => 'Дания', 'iso2_alpha_code' => 'dk'),
		23 => array('name_en' => 'United States', 'name_ru' => 'США', 'iso2_alpha_code' => 'us'),
		24 => array('name_en' => 'Canada', 'name_ru' => 'Канада', 'iso2_alpha_code' => 'ca'),
		25 => array('name_en' => 'Mexico', 'name_ru' => 'Мексика', 'iso2_alpha_code' => 'mx'),
		26 => array('name_en' => 'Bermuda', 'name_ru' => 'Бермуды', 'iso2_alpha_code' => 'bm'),
		27 => array('name_en' => 'Puerto Rico', 'name_ru' => 'Пуэрто Рико', 'iso2_alpha_code' => 'pr'),
		28 => array('name_en' => 'Virgin Islands, U.S.', 'name_ru' => 'Виргинские Острова США', 'iso2_alpha_code' => 'vi'),
		29 => array('name_en' => 'Germany', 'name_ru' => 'Германия', 'iso2_alpha_code' => 'de'),
		30 => array('name_en' => 'Iran', 'name_ru' => 'Иран', 'iso2_alpha_code' => 'ir'),
		31 => array('name_en' => 'Bolivia', 'name_ru' => 'Боливия', 'iso2_alpha_code' => 'bo'),
		32 => array('name_en' => 'Montserrat', 'name_ru' => 'Монтсеррат', 'iso2_alpha_code' => 'ms'),
		33 => array('name_en' => 'Netherlands', 'name_ru' => 'Нидерланды', 'iso2_alpha_code' => 'nl'),
		34 => array('name_en' => 'Israel', 'name_ru' => 'Израиль', 'iso2_alpha_code' => 'il'),
		35 => array('name_en' => 'Spain', 'name_ru' => 'Испания', 'iso2_alpha_code' => 'es'),
		36 => array('name_en' => 'Bahamas', 'name_ru' => 'Багамские острова', 'iso2_alpha_code' => 'bs'),
		37 => array('name_en' => 'Saint Vincent and the Grenadines', 'name_ru' => 'Сент-Винсент и Гренадины', 'iso2_alpha_code' => 'vc'),
		38 => array('name_en' => 'Chile', 'name_ru' => 'Чили', 'iso2_alpha_code' => 'cl'),
		39 => array('name_en' => 'New Caledonia', 'name_ru' => 'Новая Каледония', 'iso2_alpha_code' => 'nc'),
		40 => array('name_en' => 'Argentina', 'name_ru' => 'Аргентина', 'iso2_alpha_code' => 'ar'),
		41 => array('name_en' => 'Dominica', 'name_ru' => 'Доминика', 'iso2_alpha_code' => 'dm'),
		42 => array('name_en' => 'Singapore', 'name_ru' => 'Сингапур', 'iso2_alpha_code' => 'sg'),
		43 => array('name_en' => 'Nepal', 'name_ru' => 'Непал', 'iso2_alpha_code' => 'np'),
		44 => array('name_en' => 'Philippines', 'name_ru' => 'Филиппины', 'iso2_alpha_code' => 'ph'),
		45 => array('name_en' => 'Indonesia', 'name_ru' => 'Индонезия', 'iso2_alpha_code' => 'id'),
		46 => array('name_en' => 'Pakistan', 'name_ru' => 'Пакистан', 'iso2_alpha_code' => 'pk'),
		47 => array('name_en' => 'Tokelau', 'name_ru' => 'Токелау', 'iso2_alpha_code' => 'tk'),
		48 => array('name_en' => 'New Zealand', 'name_ru' => 'Новая Зеландия', 'iso2_alpha_code' => 'nz'),
		49 => array('name_en' => 'Cambodia', 'name_ru' => 'Камбоджа', 'iso2_alpha_code' => 'kh'),
		50 => array('name_en' => 'Macau', 'name_ru' => 'Макау', 'iso2_alpha_code' => 'mo'),
		51 => array('name_en' => 'Papua New Guinea', 'name_ru' => 'Папуа Новая Гвинея', 'iso2_alpha_code' => 'pg'),
		52 => array('name_en' => 'Maldives', 'name_ru' => 'Мальдивские острова', 'iso2_alpha_code' => 'mv'),
		53 => array('name_en' => 'Afghanistan', 'name_ru' => 'Афганистан', 'iso2_alpha_code' => 'af'),
		54 => array('name_en' => 'Bangladesh', 'name_ru' => 'Бангладеш', 'iso2_alpha_code' => 'bd'),
		55 => array('name_en' => 'Ireland', 'name_ru' => 'Ирландия', 'iso2_alpha_code' => 'ie'),
		56 => array('name_en' => 'Belgium', 'name_ru' => 'Бельгия', 'iso2_alpha_code' => 'be'),
		57 => array('name_en' => 'Belize', 'name_ru' => 'Белиз', 'iso2_alpha_code' => 'bz'),
		58 => array('name_en' => 'Brazil', 'name_ru' => 'Бразилия', 'iso2_alpha_code' => 'br'),
		59 => array('name_en' => 'Switzerland', 'name_ru' => 'Швейцария', 'iso2_alpha_code' => 'ch'),
		60 => array('name_en' => 'South Africa', 'name_ru' => 'Южно-Африканская Республика', 'iso2_alpha_code' => 'za'),
		61 => array('name_en' => 'Egypt', 'name_ru' => 'Египет', 'iso2_alpha_code' => 'eg'),
		62 => array('name_en' => 'Nigeria', 'name_ru' => 'Нигерия', 'iso2_alpha_code' => 'ng'),
		63 => array('name_en' => 'Tanzania', 'name_ru' => 'Танзания', 'iso2_alpha_code' => 'tz'),
		64 => array('name_en' => 'Zambia', 'name_ru' => 'Замбия', 'iso2_alpha_code' => 'zm'),
		65 => array('name_en' => 'Senegal', 'name_ru' => 'Сенегал', 'iso2_alpha_code' => 'sn'),
		66 => array('name_en' => 'Ghana', 'name_ru' => 'Гана', 'iso2_alpha_code' => 'gh'),
		67 => array('name_en' => 'Sudan', 'name_ru' => 'Судан', 'iso2_alpha_code' => 'sd'),
		68 => array('name_en' => 'Cameroon', 'name_ru' => 'Камерун', 'iso2_alpha_code' => 'cm'),
		69 => array('name_en' => 'Malawi', 'name_ru' => 'Малави', 'iso2_alpha_code' => 'mw'),
		70 => array('name_en' => 'Angola', 'name_ru' => 'Ангола', 'iso2_alpha_code' => 'ao'),
		71 => array('name_en' => 'Kenya', 'name_ru' => 'Кения', 'iso2_alpha_code' => 'ke'),
		72 => array('name_en' => 'Gabon', 'name_ru' => 'Габон', 'iso2_alpha_code' => 'ga'),
		73 => array('name_en' => 'Mali', 'name_ru' => 'Мали', 'iso2_alpha_code' => 'ml'),
		74 => array('name_en' => 'Benin', 'name_ru' => 'Бенин', 'iso2_alpha_code' => 'bj'),
		75 => array('name_en' => 'Madagascar', 'name_ru' => 'Мадагаскар', 'iso2_alpha_code' => 'mg'),
		76 => array('name_en' => 'Chad', 'name_ru' => 'Чад', 'iso2_alpha_code' => 'td'),
		77 => array('name_en' => 'Botswana', 'name_ru' => 'Ботсвана', 'iso2_alpha_code' => 'bw'),
		78 => array('name_en' => 'Libya', 'name_ru' => 'Ливия', 'iso2_alpha_code' => 'ly'),
		79 => array('name_en' => 'Cape Verde', 'name_ru' => 'Кабо-Верде', 'iso2_alpha_code' => 'cv'),
		80 => array('name_en' => 'Rwanda', 'name_ru' => 'Руанда', 'iso2_alpha_code' => 'rw'),
		81 => array('name_en' => 'Mozambique', 'name_ru' => 'Мозамбик', 'iso2_alpha_code' => 'mz'),
		82 => array('name_en' => 'Gambia', 'name_ru' => 'Гамбия', 'iso2_alpha_code' => 'gm'),
		83 => array('name_en' => 'Lesotho', 'name_ru' => 'Лесото', 'iso2_alpha_code' => 'ls'),
		84 => array('name_en' => 'Mauritius', 'name_ru' => 'Маврикий', 'iso2_alpha_code' => 'mu'),
		85 => array('name_en' => 'Congo', 'name_ru' => 'Конго', 'iso2_alpha_code' => 'cg'),
		86 => array('name_en' => 'Uganda', 'name_ru' => 'Уганда', 'iso2_alpha_code' => 'ug'),
		87 => array('name_en' => 'Burkina Faso', 'name_ru' => 'Буркина Фасо', 'iso2_alpha_code' => 'bf'),
		88 => array('name_en' => 'Sierra Leone', 'name_ru' => 'Сьерра-Леоне', 'iso2_alpha_code' => 'sl'),
		89 => array('name_en' => 'Somalia', 'name_ru' => 'Сомали', 'iso2_alpha_code' => 'so'),
		90 => array('name_en' => 'Zimbabwe', 'name_ru' => 'Зимбабве', 'iso2_alpha_code' => 'zw'),
		91 => array('name_en' => 'Democratic Republic Of The Congo', 'name_ru' => 'Демократическая Республика Конго', 'iso2_alpha_code' => 'cd'),
		92 => array('name_en' => 'Niger', 'name_ru' => 'Нигер', 'iso2_alpha_code' => 'ne'),
		93 => array('name_en' => 'Central African Republic', 'name_ru' => 'Центрально-Африканская Республика', 'iso2_alpha_code' => 'cf'),
		94 => array('name_en' => 'Swaziland', 'name_ru' => 'Свазиленд', 'iso2_alpha_code' => 'sz'),
		95 => array('name_en' => 'Togo', 'name_ru' => 'Того', 'iso2_alpha_code' => 'tg'),
		96 => array('name_en' => 'Guinea', 'name_ru' => 'Гвинея', 'iso2_alpha_code' => 'gn'),
		97 => array('name_en' => 'Liberia', 'name_ru' => 'Либерия', 'iso2_alpha_code' => 'lr'),
		98 => array('name_en' => 'Seychelles', 'name_ru' => 'Сейшеллы', 'iso2_alpha_code' => 'sc'),
		99 => array('name_en' => 'Morocco', 'name_ru' => 'Марокко', 'iso2_alpha_code' => 'ma'),
		100 => array('name_en' => 'Algeria', 'name_ru' => 'Алжир', 'iso2_alpha_code' => 'dz'),
		101 => array('name_en' => 'Mauritania', 'name_ru' => 'Мавритания', 'iso2_alpha_code' => 'mr'),
		102 => array('name_en' => 'Namibia', 'name_ru' => 'Намибия', 'iso2_alpha_code' => 'na'),
		103 => array('name_en' => 'Djibouti', 'name_ru' => 'Джибути', 'iso2_alpha_code' => 'dj'),
		105 => array('name_en' => 'Comoros', 'name_ru' => 'Коморские острова', 'iso2_alpha_code' => 'km'),
		106 => array('name_en' => 'Reunion', 'name_ru' => 'Реюньон', 'iso2_alpha_code' => 're'),
		107 => array('name_en' => 'Equatorial Guinea', 'name_ru' => 'Экваториальная Гвинея', 'iso2_alpha_code' => 'gq'),
		108 => array('name_en' => 'Tunisia', 'name_ru' => 'Тунис', 'iso2_alpha_code' => 'tn'),
		109 => array('name_en' => 'Turkey', 'name_ru' => 'Турция', 'iso2_alpha_code' => 'tr'),
		110 => array('name_en' => 'Poland', 'name_ru' => 'Польша', 'iso2_alpha_code' => 'pl'),
		111 => array('name_en' => 'Latvia', 'name_ru' => 'Латвия', 'iso2_alpha_code' => 'lv'),
		112 => array('name_en' => 'Ukraine', 'name_ru' => 'Украина', 'iso2_alpha_code' => 'ua'),
		113 => array('name_en' => 'Belarus', 'name_ru' => 'Беларусь', 'iso2_alpha_code' => 'by'),
		114 => array('name_en' => 'Czech Republic', 'name_ru' => 'Чехия', 'iso2_alpha_code' => 'cz'),
		115 => array('name_en' => 'Palestinian Territory', 'name_ru' => 'Палестина', 'iso2_alpha_code' => 'ps'),
		116 => array('name_en' => 'Iceland', 'name_ru' => 'Исландия', 'iso2_alpha_code' => 'is'),
		117 => array('name_en' => 'Cyprus', 'name_ru' => 'Кипр', 'iso2_alpha_code' => 'cy'),
		118 => array('name_en' => 'Hungary', 'name_ru' => 'Венгрия', 'iso2_alpha_code' => 'hu'),
		119 => array('name_en' => 'Slovakia', 'name_ru' => 'Словакия', 'iso2_alpha_code' => 'sk'),
		120 => array('name_en' => 'Serbia', 'name_ru' => 'Сербия', 'iso2_alpha_code' => 'rs'),
		121 => array('name_en' => 'Bulgaria', 'name_ru' => 'Болгария', 'iso2_alpha_code' => 'bg'),
		122 => array('name_en' => 'Oman', 'name_ru' => 'Оман', 'iso2_alpha_code' => 'om'),
		123 => array('name_en' => 'Romania', 'name_ru' => 'Румыния', 'iso2_alpha_code' => 'ro'),
		124 => array('name_en' => 'Georgia', 'name_ru' => 'Грузия', 'iso2_alpha_code' => 'ge'),
		125 => array('name_en' => 'Norway', 'name_ru' => 'Норвегия', 'iso2_alpha_code' => 'no'),
		126 => array('name_en' => 'Armenia', 'name_ru' => 'Армения', 'iso2_alpha_code' => 'am'),
		127 => array('name_en' => 'Austria', 'name_ru' => 'Австрия', 'iso2_alpha_code' => 'at'),
		128 => array('name_en' => 'Albania', 'name_ru' => 'Албания', 'iso2_alpha_code' => 'al'),
		129 => array('name_en' => 'Slovenia', 'name_ru' => 'Словения', 'iso2_alpha_code' => 'si'),
		130 => array('name_en' => 'Panama', 'name_ru' => 'Панама', 'iso2_alpha_code' => 'pa'),
		131 => array('name_en' => 'Brunei Darussalam', 'name_ru' => 'Бруней', 'iso2_alpha_code' => 'bn'),
		132 => array('name_en' => 'Sri Lanka', 'name_ru' => 'Шри-Ланка', 'iso2_alpha_code' => 'lk'),
		133 => array('name_en' => 'Montenegro', 'name_ru' => 'Черногория', 'iso2_alpha_code' => 'me'),
		134 => array('name_en' => 'Europe', 'name_ru' => 'Европейский Союз', 'iso2_alpha_code' => 'eu'),
		135 => array('name_en' => 'Tajikistan', 'name_ru' => 'Таджикистан', 'iso2_alpha_code' => 'tj'),
		136 => array('name_en' => 'Iraq', 'name_ru' => 'Ирак', 'iso2_alpha_code' => 'iq'),
		137 => array('name_en' => 'Lebanon', 'name_ru' => 'Ливан', 'iso2_alpha_code' => 'lb'),
		138 => array('name_en' => 'Moldova', 'name_ru' => 'Молдова', 'iso2_alpha_code' => 'md'),
		139 => array('name_en' => 'Finland', 'name_ru' => 'Финляндия', 'iso2_alpha_code' => 'fi'),
		140 => array('name_en' => 'Estonia', 'name_ru' => 'Эстония', 'iso2_alpha_code' => 'ee'),
		141 => array('name_en' => 'Bosnia and Herzegovina', 'name_ru' => 'Босния и Герцеговина', 'iso2_alpha_code' => 'ba'),
		142 => array('name_en' => 'Kuwait', 'name_ru' => 'Кувейт', 'iso2_alpha_code' => 'kw'),
		143 => array('name_en' => 'Aland Islands', 'name_ru' => 'Аландские острова', 'iso2_alpha_code' => 'ax'),
		144 => array('name_en' => 'Lithuania', 'name_ru' => 'Литва', 'iso2_alpha_code' => 'lt'),
		145 => array('name_en' => 'Luxembourg', 'name_ru' => 'Люксембург', 'iso2_alpha_code' => 'lu'),
		146 => array('name_en' => 'Antigua and Barbuda', 'name_ru' => 'Антигуа и Барбуда', 'iso2_alpha_code' => 'ag'),
		147 => array('name_en' => 'Macedonia', 'name_ru' => 'Македония', 'iso2_alpha_code' => 'mk'),
		148 => array('name_en' => 'San Marino', 'name_ru' => 'Сан-Марино', 'iso2_alpha_code' => 'sm'),
		149 => array('name_en' => 'Malta', 'name_ru' => 'Мальта', 'iso2_alpha_code' => 'mt'),
		150 => array('name_en' => 'Falkland Islands', 'name_ru' => 'Фолклендские острова', 'iso2_alpha_code' => 'fk'),
		151 => array('name_en' => 'Bahrain', 'name_ru' => 'Бахрейн', 'iso2_alpha_code' => 'bh'),
		152 => array('name_en' => 'Uzbekistan', 'name_ru' => 'Узбекистан', 'iso2_alpha_code' => 'uz'),
		153 => array('name_en' => 'Azerbaijan', 'name_ru' => 'Азербайджан', 'iso2_alpha_code' => 'az'),
		154 => array('name_en' => 'Monaco', 'name_ru' => 'Монако', 'iso2_alpha_code' => 'mc'),
		155 => array('name_en' => 'Haiti', 'name_ru' => 'Гаити', 'iso2_alpha_code' => 'ht'),
		156 => array('name_en' => 'Guam', 'name_ru' => 'Гуам', 'iso2_alpha_code' => 'gu'),
		157 => array('name_en' => 'Jamaica', 'name_ru' => 'Ямайка', 'iso2_alpha_code' => 'jm'),
		158 => array('name_en' => 'United States Minor Outlying Islands', 'name_ru' => 'Внешние малые острова США', 'iso2_alpha_code' => 'um'),
		159 => array('name_en' => 'Micronesia', 'name_ru' => 'Микронезия', 'iso2_alpha_code' => 'fm'),
		160 => array('name_en' => 'Ecuador', 'name_ru' => 'Эквадор', 'iso2_alpha_code' => 'ec'),
		161 => array('name_en' => 'Peru', 'name_ru' => 'Перу', 'iso2_alpha_code' => 'pe'),
		162 => array('name_en' => 'Cayman Islands', 'name_ru' => 'Каймановы острова', 'iso2_alpha_code' => 'ky'),
		163 => array('name_en' => 'Colombia', 'name_ru' => 'Колумбия', 'iso2_alpha_code' => 'co'),
		164 => array('name_en' => 'Honduras', 'name_ru' => 'Гондурас', 'iso2_alpha_code' => 'hn'),
		165 => array('name_en' => 'Netherlands Antilles', 'name_ru' => 'Антильские острова', 'iso2_alpha_code' => 'an'),
		166 => array('name_en' => 'Yemen', 'name_ru' => 'Йемен', 'iso2_alpha_code' => 'ye'),
		167 => array('name_en' => 'Virgin Islands, British', 'name_ru' => 'Британские Виргинские острова', 'iso2_alpha_code' => 'vg'),
		168 => array('name_en' => 'Syria', 'name_ru' => 'Сирия', 'iso2_alpha_code' => 'sy'),
		169 => array('name_en' => 'Nicaragua', 'name_ru' => 'Никарагуа', 'iso2_alpha_code' => 'ni'),
		170 => array('name_en' => 'Dominican Republic', 'name_ru' => 'Доминиканская республика', 'iso2_alpha_code' => 'do'),
		171 => array('name_en' => 'Grenada', 'name_ru' => 'Гренада', 'iso2_alpha_code' => 'gd'),
		172 => array('name_en' => 'Guatemala', 'name_ru' => 'Гватемала', 'iso2_alpha_code' => 'gt'),
		173 => array('name_en' => 'Costa Rica', 'name_ru' => 'Коста-Рика', 'iso2_alpha_code' => 'cr'),
		174 => array('name_en' => 'El Salvador', 'name_ru' => 'Сальвадор', 'iso2_alpha_code' => 'sv'),
		175 => array('name_en' => 'Venezuela', 'name_ru' => 'Венесуэла', 'iso2_alpha_code' => 've'),
		176 => array('name_en' => 'Barbados', 'name_ru' => 'Барбадос', 'iso2_alpha_code' => 'bb'),
		177 => array('name_en' => 'Trinidad and Tobago', 'name_ru' => 'Тринидад и Тобаго', 'iso2_alpha_code' => 'tt'),
		178 => array('name_en' => 'Bouvet Island', 'name_ru' => 'Буве', 'iso2_alpha_code' => 'bv'),
		179 => array('name_en' => 'Marshall Islands', 'name_ru' => 'Маршалловы острова', 'iso2_alpha_code' => 'mh'),
		180 => array('name_en' => 'Cook Islands', 'name_ru' => 'Острова Кука', 'iso2_alpha_code' => 'ck'),
		181 => array('name_en' => 'Gibraltar', 'name_ru' => 'Гибралтар', 'iso2_alpha_code' => 'gi'),
		182 => array('name_en' => 'Paraguay', 'name_ru' => 'Парагвай', 'iso2_alpha_code' => 'py'),
		184 => array('name_en' => 'Samoa', 'name_ru' => 'Самоа', 'iso2_alpha_code' => 'ws'),
		185 => array('name_en' => 'Saint Kitts and Nevis', 'name_ru' => 'Сент Китс и Невис', 'iso2_alpha_code' => 'kn'),
		186 => array('name_en' => 'Fiji', 'name_ru' => 'Фиджи', 'iso2_alpha_code' => 'fj'),
		187 => array('name_en' => 'Uruguay', 'name_ru' => 'Уругвай', 'iso2_alpha_code' => 'uy'),
		188 => array('name_en' => 'Northern Mariana Islands', 'name_ru' => 'Северные Марианские острова', 'iso2_alpha_code' => 'mp'),
		189 => array('name_en' => 'Palau', 'name_ru' => 'Палау', 'iso2_alpha_code' => 'pw'),
		190 => array('name_en' => 'Qatar', 'name_ru' => 'Катар', 'iso2_alpha_code' => 'qa'),
		191 => array('name_en' => 'Jordan', 'name_ru' => 'Иордания', 'iso2_alpha_code' => 'jo'),
		192 => array('name_en' => 'American Samoa', 'name_ru' => 'Американское Самоа', 'iso2_alpha_code' => 'as'),
		193 => array('name_en' => 'Turks and Caicos Islands', 'name_ru' => 'Туркс и Кейкос', 'iso2_alpha_code' => 'tc'),
		194 => array('name_en' => 'Saint Lucia', 'name_ru' => 'Святая Люсия', 'iso2_alpha_code' => 'lc'),
		195 => array('name_en' => 'Mongolia', 'name_ru' => 'Монголия', 'iso2_alpha_code' => 'mn'),
		196 => array('name_en' => 'Holy See', 'name_ru' => 'Ватикан', 'iso2_alpha_code' => 'va'),
		197 => array('name_en' => 'Aruba', 'name_ru' => 'Арулько', 'iso2_alpha_code' => 'aw'),
		198 => array('name_en' => 'Guyana', 'name_ru' => 'Гайана', 'iso2_alpha_code' => 'gy'),
		199 => array('name_en' => 'Suriname', 'name_ru' => 'Суринам', 'iso2_alpha_code' => 'sr'),
		200 => array('name_en' => 'Isle of Man', 'name_ru' => 'Остров Мэн', 'iso2_alpha_code' => 'im'),
		201 => array('name_en' => 'Vanuatu', 'name_ru' => 'Вануату', 'iso2_alpha_code' => 'vu'),
		202 => array('name_en' => 'Croatia', 'name_ru' => 'Хорватия', 'iso2_alpha_code' => 'hr'),
		203 => array('name_en' => 'Anguilla', 'name_ru' => 'Ангуилья', 'iso2_alpha_code' => 'ai'),
		204 => array('name_en' => 'Saint Pierre and Miquelon', 'name_ru' => 'Сен-Пьер и Микелон', 'iso2_alpha_code' => 'pm'),
		205 => array('name_en' => 'Guadeloupe', 'name_ru' => 'Гваделупа', 'iso2_alpha_code' => 'gp'),
		206 => array('name_en' => 'Saint Martin', 'name_ru' => 'Сен-Мартен', 'iso2_alpha_code' => 'mf'),
		207 => array('name_en' => 'Guernsey', 'name_ru' => 'Гернси', 'iso2_alpha_code' => 'gg'),
		208 => array('name_en' => 'Burundi', 'name_ru' => 'Бурунди', 'iso2_alpha_code' => 'bi'),
		209 => array('name_en' => 'Turkmenistan', 'name_ru' => 'Туркменистан', 'iso2_alpha_code' => 'tm'),
		210 => array('name_en' => 'Kyrgyzstan', 'name_ru' => 'Кыргызстан', 'iso2_alpha_code' => 'kg'),
		211 => array('name_en' => 'Myanmar', 'name_ru' => 'Мьянма', 'iso2_alpha_code' => 'mm'),
		212 => array('name_en' => 'Bhutan', 'name_ru' => 'Бутан', 'iso2_alpha_code' => 'bt'),
		213 => array('name_en' => 'Liechtenstein', 'name_ru' => 'Лихтенштейн', 'iso2_alpha_code' => 'li'),
		214 => array('name_en' => 'Faroe Islands', 'name_ru' => 'Фарерские острова', 'iso2_alpha_code' => 'fo'),
		215 => array('name_en' => 'Ethiopia', 'name_ru' => 'Эфиопия', 'iso2_alpha_code' => 'et'),
		216 => array('name_en' => 'Martinique', 'name_ru' => 'Мартиника', 'iso2_alpha_code' => 'mq'),
		217 => array('name_en' => 'Jersey', 'name_ru' => 'Джерси', 'iso2_alpha_code' => 'je'),
		218 => array('name_en' => 'Andorra', 'name_ru' => 'Андорра', 'iso2_alpha_code' => 'ad'),
		219 => array('name_en' => 'Antarctica', 'name_ru' => 'Антарктида', 'iso2_alpha_code' => 'aq'),
		220 => array('name_en' => 'British Indian Ocean Territory', 'name_ru' => 'Британская территория в Индийском океане', 'iso2_alpha_code' => 'io'),
		221 => array('name_en' => 'Greenland', 'name_ru' => 'Гренландия', 'iso2_alpha_code' => 'gl'),
		222 => array('name_en' => 'Guinea-Bissau', 'name_ru' => 'Гвинея-Бисау', 'iso2_alpha_code' => 'gw'),
		223 => array('name_en' => 'Eritrea', 'name_ru' => 'Эритрея', 'iso2_alpha_code' => 'er'),
		224 => array('name_en' => 'Wallis and Futuna', 'name_ru' => 'Уоллис и Футуна', 'iso2_alpha_code' => 'wf'),
		225 => array('name_en' => 'French Polynesia', 'name_ru' => 'Французская Полинезия', 'iso2_alpha_code' => 'pf'),
		226 => array('name_en' => 'Cuba', 'name_ru' => 'Куба', 'iso2_alpha_code' => 'cu'),
		227 => array('name_en' => 'Tonga', 'name_ru' => 'Тонга', 'iso2_alpha_code' => 'to'),
		228 => array('name_en' => 'Timor-Leste', 'name_ru' => 'Восточный Тимор', 'iso2_alpha_code' => 'tl'),
		229 => array('name_en' => 'Sao Tome and Principe', 'name_ru' => 'Сан-Томе и Принсипи', 'iso2_alpha_code' => 'st'),
		230 => array('name_en' => 'French Guiana', 'name_ru' => 'Французская Гвинея', 'iso2_alpha_code' => 'gf'),
		231 => array('name_en' => 'Solomon Islands', 'name_ru' => 'Соломоновы острова', 'iso2_alpha_code' => 'sb'),
		232 => array('name_en' => 'Tuvalu', 'name_ru' => 'Тувалу', 'iso2_alpha_code' => 'tv'),
		233 => array('name_en' => 'Kiribati', 'name_ru' => 'Кирибати', 'iso2_alpha_code' => 'ki'),
		234 => array('name_en' => 'Niue', 'name_ru' => 'Ниуэ', 'iso2_alpha_code' => 'nu'),
		235 => array('name_en' => 'Norfolk Island', 'name_ru' => 'Норфолк', 'iso2_alpha_code' => 'nf'),
		236 => array('name_en' => 'Nauru', 'name_ru' => 'Науру', 'iso2_alpha_code' => 'nr'),
		237 => array('name_en' => 'Mayotte', 'name_ru' => 'Майотта', 'iso2_alpha_code' => 'yt'),
		238 => array('name_en' => 'Pitcairn Islands', 'name_ru' => 'Питкэрн', 'iso2_alpha_code' => 'pn'),
		239 => array('name_en' => 'Cote DIvoire', 'name_ru' => 'Кот-дИвуар', 'iso2_alpha_code' => 'ci'),
		240 => array('name_en' => 'Lao', 'name_ru' => 'Лаос', 'iso2_alpha_code' => 'la'),
		241 => array('name_en' => 'Democratic Peoples Republic of Korea', 'name_ru' => 'Корейская Народно-Демократическая Республика', 'iso2_alpha_code' => 'kp'),
		242 => array('name_en' => 'Svalbard and Jan Mayen', 'name_ru' => 'Свальбард и Ян-Майен', 'iso2_alpha_code' => 'sj'),
		243 => array('name_en' => 'Saint Helena', 'name_ru' => 'Остров Святой Елены', 'iso2_alpha_code' => 'sh'),
		244 => array('name_en' => 'Cocos (Keeling) Islands', 'name_ru' => 'Кокосовые острова', 'iso2_alpha_code' => 'cc'),
		245 => array('name_en' => 'Western Sahara', 'name_ru' => 'Западная Сахара', 'iso2_alpha_code' => 'eh'),
		247 => array('name_en' => 'South Sudan', 'name_ru' => 'Южный Судан', 'iso2_alpha_code' => 'ss')
);
